from nginx
run echo "nice to meet you! docker"
run touch hello_world.txt
add b1_updated.txt test.txt
run echo "b1 branch after update"
run echo "b1 branch after second update"
run echo "b1 branch after third update"
run echo "b1 branch after fourth update"
run echo "b1 branch after fifth update"
run echo "b1 branch after sixth update"
